# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Palabras
paginate:       5
baseurl:        "/palabras"
url:            "https://thessaly.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Julieta
  url:          
  email:        julieta@rlab.be

# Custom vars
version:       
github:
  repo:         
  
# Gems
plugins:
  - jekyll-paginate
